### ISSUE TITLE
Not returning partial search

### ISSUE THREAD

**Issue by joshharington** [mustafaaloko/elasticquent5#8]
I am trying to create a search on user profiles on my website. If I search "Josh" it returns the Profile object that has "Josh", but if I search "Jo" it returns nothing. The code is copy pasted from the instructions on this repo. Any ideas on how to fix this?

**Comment by joshharington** [comment]
Solved by using 'searchByQuery' instead of 'search'. So my whole line instead of:

`Profile::search(Input::get('search_term'))`

I used 

`Profile::searchByQuery(array('query_string' => array('query' => '*' . Input::get('search_term') . '*' )))`

**Comment by mustafaaloko** [comment]
Great then! 👍
